app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout

homepage:
    path: /
    controller: App\Controller\IndexController::index

app_register:
    path: /registration
    controller: App\Controller\LoginController::registration

post_create:
    path: /post/create
    controller: App\Controller\Admin\BlogController::createPost

post_edit:
    path: /post/{post}/edit
    controller: App\Controller\Admin\BlogController::editPost
    requirements:
        post: '\d+'