app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout

homepage:
    path: /
    controller: App\Controller\IndexController::index

app_register:
    path: /registration
    controller: App\Controller\LoginController::registration

post_create:
    path: /admin/post/create
    controller: App\Controller\Admin\BlogController::createPost

post_edit:
    path: /admin/post/{post}/edit
    controller: App\Controller\Admin\BlogController::editPost
    requirements:
        post: '\d+'

comment_create:
    path: /post/{post}/comment/create
    controller: App\Controller\User\BlogController::createComment
    requirements:
        post: '\d+'

comment_edit:
    path: /post/{post}/comment/{comment}/edit
    controller: App\Controller\User\BlogController::editComment
    requirements:
        comment: '\d+'
        post: '\d+'

comment_to_approve_list:
    path: /admin/commentsToApprove
    controller: App\Controller\Admin\BlogController::commentsToApprove


comment_approve:
    path: /admin/comment/{comment}/approve
    controller: App\Controller\Admin\BlogController::commentApprove
    requirements:
        comment: '\d+'

comment_reject:
    path: /admin/comment/{comment}/reject
    controller: App\Controller\Admin\BlogController::commentReject
    requirements:
        comment: '\d+'

comment_delete:
    path: /admin/comment/{comment}/delete
    controller: App\Controller\Admin\BlogController::commentDelete
    requirements:
        comment: '\d+'